# Generated by Django 3.1.2 on 2021-04-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_orderproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='text-product'),
            preserve_default=False,
        ),
    ]
