# Generated by Django 3.1.2 on 2021-04-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='producto',
            field=models.ManyToManyField(to='core.OrderProducto'),
        ),
    ]
