# Generated by Django 3.1.2 on 2021-04-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210423_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducto',
            name='ordered',
        ),
    ]
