# Generated by Django 3.1.2 on 2021-04-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_orderproducto_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
