# Generated by Django 3.1.2 on 2021-05-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210510_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionfactura',
            name='opcion_de_pago',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
