# Generated by Django 3.1.2 on 2021-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210514_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
