# Generated by Django 3.1.2 on 2021-05-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210514_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
