# Generated by Django 3.1.2 on 2021-06-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210623_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Herramienta', 'Herramienta'), ('Indumentaria', 'Indumentaria'), ('Iluminación', 'Iluminación_Y_Redes'), ('Material', 'Material'), ('Madera', 'Madera')], max_length=20),
        ),
    ]
