# Generated by Django 3.1.2 on 2021-06-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210623_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idMod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
