# Generated by Django 3.1.2 on 2021-06-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_tipoproducto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='SKU',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
