# Generated by Django 3.1.2 on 2021-06-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210624_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stockCritico',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
