# Generated by Django 3.1.2 on 2021-06-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_tipofamilia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipoFamilia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.tipofamilia'),
            preserve_default=False,
        ),
    ]
