# Generated by Django 3.1.2 on 2021-06-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_producto_tipofamilia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rango',
        ),
    ]
