# Generated by Django 3.1.2 on 2021-06-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delete_rango'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('telefono', models.IntegerField()),
                ('rubro', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
