# Generated by Django 3.1.2 on 2021-07-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_proveedor_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='idMod',
        ),
    ]
