# Generated by Django 3.1.2 on 2021-07-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_producto_idmod'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fechaVenc',
            field=models.DateField(default='2021-09-12'),
            preserve_default=False,
        ),
    ]
