# Generated by Django 3.1.2 on 2021-05-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rango',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('VEN', 'Vendedor'), ('EMP', 'Empleado'), ('CLI', 'Cliente'), ('PRO', 'Proveedor')], default='CLI', max_length=3),
        ),
    ]
